"""
Django settings for wellnet project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from django.contrib import messages

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*a^ymn+15j@u=p3d2l47q*2(qgtytz#+tx+vwia*f-+-^ronus'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost','127.0.0.1',
                                 '.wellnetservices.com', 'wellnetservices.com',
            'code.jquery.com','.googleapis.com','http://sales.wellnetservices.com',]

AUTH_USER_MODEL = "services.BaseUser"

ADMINS = (
    ('prakash', 'prakash.t@forktechnologies.com'),
)

# Application definition
USE_DJANGO_JQUERY = True
INSTALLED_APPS = (
    # 'material',
    # 'material.admin',
    # 'bootstrap3',
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'wkhtmltopdf',
    'services',
    'django_select2',
    'smart_selects',
    'datetimewidget',
    'django_cron',
    'mathfilters'
)
DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer'

SITE_ID = 1

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'services.middleware.PasswordChangeMiddleware'
)

ROOT_URLCONF = 'wellnet.urls'

CRON_CLASSES = [
    "services.jobs.ServiceReminder",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wellnet.wsgi.application'
BOOTSTRAP_ADMIN_SIDEBAR_MENU = True
LOGIN_URL = '/admin/login'
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'wellnet_new',
            'USER': 'assessment',
            'PASSWORD': '',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }

CACHES = {
    "default": {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11212',
    },
    'select2': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 86400
    }
}
# Set the cache backend to select2
SELECT2_CACHE_BACKEND = 'select2'
SELECT2_CACHE_PREFIX = 'SELECT2_'

if DEBUG:
    EMAIL_USE_TLS = True
    EMAIL_HOST = 'mail.forktechnologies.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = 'prakash.t@forktechnologies.com'
    EMAIL_HOST_PASSWORD = 'quti8147'
    DEFAULT_FROM_EMAIL = 'prakash.t@forktechnologies.com'
    DEFAULT_TO_EMAIL = 'prakash.t@forktechnologies.com'
else:
    EMAIL_HOST = 'mail.wellnetservices.com'
    EMAIL_HOST_USER = 'no-reply@wellnetservices.com'
    EMAIL_HOST_PASSWORD = 'wellnet@123'
    DEFAULT_FROM_EMAIL = 'no-reply@wellnetservices.com'
    SERVER_EMAIL = 'no-reply@wellnetservices.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = False

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = False

USE_L10N = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
if DEBUG:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, "static/services")
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
else:
    STATIC_URL = 'http://sales.wellnetservices.com/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, "static/services")
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MESSAGE_TAGS = {
    messages.SUCCESS: 'alert-success success',
    messages.WARNING: 'alert-warning warning',
    messages.ERROR: 'alert-danger error'
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'server.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'services': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
}

DATE_INPUT_FORMATS = ('%Y-%m-%d', '%d/%m/%Y', '%d-%m-%Y', '%d/%m/%y', '%d %b %Y',
                      '%d %b, %Y', '%d %b %Y', '%d %b, %Y', '%d %B, %Y',
                      '%d %B %Y')
DATETIME_INPUT_FORMATS = ('%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M', '%d/%m/%Y',
                          '%d/%m/%y %H:%M:%S', '%d/%m/%y %H:%M', '%d/%m/%y',
                          '%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M', '%Y-%m-%d')
if not DEBUG:
    WKHTMLTOPDF_CMD = '/opt/wellnet_server/wkhtmltopdf.sh'

EKONNECT_ACCOUNT_ID = "2d32469b-e4b7-4d51-934d-fcbd4b55c368"
EKONNECT_NEW_BOOKING_TEMPLATE_ID = "24e4bc65-c32a-4ff2-ac9b-5ced75df0d1a"
EKONNECT_NEW_ORDER_TEMPLATE_ID = "698f647c-7435-4045-9ba0-bba04869be25"
EKONNECT_NEW_ORDER_V2_TEMPLATE_ID = "14abb79b-613a-40b6-b75d-90f5d9242f50"
EKONNECT_SERVICE_REMAINDER_TEMPLATE_ID = "3b44616c-7f40-4a93-a495-f2ae7811312a"
EKONNECT_NEW_PARTNER_TEMPLATE_ID = "7cdbcda5-a1db-471f-950e-d8746c5b1984"
# Dealer network service
BACTAKLEEN_SERVICE_BOOKING_TEMPLATE_NAME_TO_CUSTOMER1 = "Wellnet_Service_booking_customer1"
BACTAKLEEN_SERVICE_BOOKING_TEMPLATE_NAME_TO_DEALER1 = "Wellnet_Service_booking_dealer1"
BACTAKLEEN_SERVICE_BOOKING_TEMPLATE_NAME_TO_CUSTOMER2 = "Wellnet_Service_booking_customer2"
BACTAKLEEN_SERVICE_BOOKING_TEMPLATE_NAME_TO_DEALER2 = "Wellnet_Service_booking_dealer2"
